name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  python-test:
    name: Python Tests (pytest in container)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get file architecture
        run: pwd && ls -R

      - name: DEBUG ECHO ENV
        run: echo "${{ env.GITHUB_PATH }} $GITHUB_WORKSPACE"

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'  # Active le cache pip
          pip-install: -r Bot/requirements-dev.txt

      - name: Run tests
        working-directory: Bot
        run: python -m pytest (echo $GITHUB_WORKSPACE)/tests/test_backtesting_coherence.py

  secrets-scan:
    name: Scan for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}